name: Linux Demo
on:
  push
jobs:
  success-case:
    runs-on: ubuntu-latest
    name: Successful case
    steps:
    - uses: actions/checkout@v2
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      run: python linuxrunner.py -- ./testapp -t 5

  crash-case:
    runs-on: ubuntu-latest
    name: Crash case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running crashed program
      id: running
      shell: bash
      continue-on-error: true
      run: |
        python linuxrunner.py -t 60 -- ./testapp -t 5 -c
    - name: check result
      run: |
        if test "${{ steps.running.outcome }}" != "failure"; then
          echo Expecting failure in the previous step but got "${{ steps.running.outcome }}"
          exit 777
        else
          echo Previous step fails as expected
          exit 0
        fi

  timeout-case:
    runs-on: ubuntu-latest
    name: Timeout case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      id: running
      shell: bash
      continue-on-error: true
      run: |
        python linuxrunner.py -t 5 -- ./testapp -t 60
    - name: check result
      run: |
        if test "${{ steps.running.outcome }}" != "failure"; then
          echo Expecting failure in the previous step but got "${{ steps.running.outcome }}"
          exit 777
        else
          echo Previous step fails as expected
          exit 0
        fi

