name: Linux Demo
on:
  push
jobs:
  success-case:
    runs-on: ubuntu-latest
    name: Successful case
    steps:
    - uses: actions/checkout@v2
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      run: python cirunner.py -o linux-success -- ./testapp -t 5
    - name: Upload artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: linux-crash

  crash-case:
    runs-on: ubuntu-latest
    name: Crash case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running crashed program
      id: running
      shell: bash
      run: |
        python cirunner.py -t 60 -o linux-crash -- ./testapp -t 5 -c
    - name: Upload artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: linux-crash
    - name: check result
      if: ${{ always() }}
      run: |
        if test "${{ steps.running.outcome }}" != "failure"; then
          echo Expecting failure in the previous step but got "${{ steps.running.outcome }}"
          exit 777
        else
          echo Previous step failed as expected
          exit 0
        fi

  timeout-case:
    runs-on: ubuntu-latest
    name: Timeout case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installlinux.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      id: running
      shell: bash
      run: |
        python cirunner.py -t 5 -o linux-timeout -- ./testapp -t 60
    - name: Upload artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: linux-timeout
    - name: check result
      if: ${{ always() }}
      run: |
        if test "${{ steps.running.outcome }}" != "failure"; then
          echo Expecting failure in the previous step but got "${{ steps.running.outcome }}"
          exit 777
        else
          echo Previous step failed as expected
          exit 0
        fi

