name: Mac Demo
on:
  push
jobs:
  success-case:
    runs-on: macos-latest
    name: Successful case
    steps:
    - uses: actions/checkout@v2
    - name: install cirunner infrastructure
      run: ./installmac.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      run: python macrunner.py -- ./testapp -t 5

  crash-case:
    runs-on: macos-latest
    name: Crash case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installmac.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      shell: bash
      continue-on-error: true
      run: |
        # Runner will return non-zero if the test program fails, and this will fail the job.
        # So use commands below to save return value and set exit code to 0.
        python macrunner.py -t 60 -- ./testapp -t 5 -c; ret=$?; true; true
        if test $ret -eq 0; then
          echo Error: expecting failure
          exit 777
        fi
        exit 0

