name: Mac Demo
on:
  push
jobs:
  success-case:
    runs-on: macos-latest
    name: Successful case
    steps:
    - uses: actions/checkout@v2
    - name: install cirunner infrastructure
      run: ./installmac.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      run: python macrunner.py -- ./testapp -t 5

  crash-case:
    runs-on: macos-latest
    name: Crash case
    steps:
    - uses: actions/checkout@master
    - name: install cirunner infrastructure
      run: ./installmac.sh
    - name: build testapp
      run: |
        gcc -o testapp -O0 -g testapp.c
    - name: running test program
      shell: bash
      continue-on-error: true
      run: |
        ulimit -c unlimited
        ./testapp -t 5 -c
    - name: examine crash
      shell: bash
      run: |
        echo ls -l /cores
        ls -l /cores
        core=`ls /cores/core.*` | head -1
        echo core file is $core
        lldb --core $core -o 'bt all' -o quit ./testapp

