name: Windows Demo
on:
  push
jobs:
  success-case:
    runs-on: windows-latest
    name: Successful case
    steps:
    - uses: actions/checkout@master
    - name: install crash handler registry
      run: start-process cmd.exe -Verb runAs -ArgumentList ("/C", "cd", $(Get-Location), "&&", "reg.exe", "IMPORT", "localdumps.reg")
    - name: install ci-runner
      run: |
        pip install -r requirements.txt
        python winrunner.py -i
    - name: build testapp
      run: |
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cl.exe /nologo /Od /Zi testapp.c
      shell: cmd
    - name: run
      run: python winrunner.py -- testapp.exe -t 5

  crash-case:
    runs-on: windows-latest
    name: Crash case
    steps:
    - uses: actions/checkout@master
    - name: install crash handler registry
      run: start-process cmd.exe -Verb runAs -ArgumentList ("/C", "cd", $(Get-Location), "&&", "reg.exe", "IMPORT", "localdumps.reg")
    - name: install ci-runner
      run: |
        pip install -r requirements.txt
        python winrunner.py -i
    - name: build testapp
      run: |
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cl.exe /nologo /Od /Zi testapp.c
      shell: cmd
    - name: run
      run: |
        # Runner will return non-zero if the test program fails, but this will fail the job.
        # So use commands below to save return value to $ret instead.
        python winrunner.py -t 60 -- testapp.exe -t 5 -c; $ret=$lastexitcode; cmd /C exit 0
        if ($ret -eq 0) {
          cmd /C exit 1
        }

  timeout-case:
    runs-on: windows-latest
    name: Timeout case
    steps:
    - uses: actions/checkout@master
    - name: install crash handler registry
      run: start-process cmd.exe -Verb runAs -ArgumentList ("/C", "cd", $(Get-Location), "&&", "reg.exe", "IMPORT", "localdumps.reg")
    - name: install ci-runner
      run: |
        pip install -r requirements.txt
        python winrunner.py -i
    - name: build testapp
      run: |
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        cl.exe /nologo /Od /Zi testapp.c
      shell: cmd
    - name: run
      run: |
        # Runner will return non-zero if the test program fails, but this will fail the job.
        # So use commands below to save return value to $ret instead.
        #python winrunner.py -t 5 -- testapp.exe -t 60; $ret=$lastexitcode; cmd /C exit 0
        python winrunner.py -- testapp.exe -t 5; $ret=$lastexitcode; cmd /C exit 0
        if ($ret -eq 0) {
          cmd /C exit 1
        }
